on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
#diferencia entre run y uses , run sirve para definir un comando una accion que realiza
#uses usa accion preempaquetada de github
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: descarga del codigo
        uses: actions/checkout@v3
      - name: instalacion de version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: instalacion depencia
        run: npm install
      - name: correr test
        run: npm test